name: Feedback Report
description: File a feedback report
title: "LAB00: QUICK_DESCRIPTION"
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this feedback report!
        
        **Replace the feedback title LAB00: QUICK_DESCRIPTION, for example "LAB01: My new feedback"**
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info 😉?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What should we change?
      description: What should we change?
      placeholder: Tell us your proposal!
      value: PROPOSAL
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Lab
      description: Which lab does this feedback relate to?
      options:
        - Other
        - Lab 00 Setup
        - Lab 01 Explore Microsoft Entra ID User Settings
        - Lab 02 Microsoft Entra self-service password reset
        - Lab 03 Microsoft Entra Conditional Access
        - Lab 04 Explore Privileged Identity management
        - Lab 05 Explore Azure Network Security Groups (NSGs)
        - Lab 06 Explore Microsoft Defender for Cloud
        - Lab 07 Explore Microsoft Sentinel
        - Lab 08 Explore Microsoft Defender for Cloud Apps
        - Lab 09 Explore the Microsoft 365 Defender portal
        - Lab 11 Explore the Service Trust Portal
        - Lab 12 Explore the Microsoft Purview compliance portal & Compliance Manager
        - Lab 13 Explore sensitivity labels in Microsoft Purview
        - Lab 14 Explore insider risk management in Microsoft Purview
        - Lab 15 Explore the eDiscovery (Standard) workflow
    validations:
      required: true
  - type: textarea
    id: Screenshots
    attributes:
      label: Relevant screenshots
      description: Please copy and paste any relevant screenshots 📸
      value: paste here 😉 
  
